version: 1.0.{build}
before_build:
- cmd: nuget restore AppVeyorCITesting.sln
build:
  project: AppVeyorCITesting.sln
  verbosity: minimal
test: off
environment:
  COVERALLS_REPO_TOKEN:
    secure: 3BmUK4nB8kdRgKzgTbp0wNVonHANhUb7qQ8UxTDhkn2tXnvNHMgyhmxKAxL2j+Tc
after_build:
- cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.2.1\tools\nunit3-console.exe" -targetargs:"/domain:single AppVeyorCITesting\AppVeyorCITesting.Tests\bin\Debug\AppVeyorCITesting.Tests.dll" -output:coverage.xml
- cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
artifacts:
  - path: AppVeyorCITesting\AppVeyorCITesting\bin\Debug\*.*
    name: release-deploy.zip
deploy:
  provider: S3
  access_key_id: AKIAIQEGAB4SXNC5N6AQ
  secret_access_key:
    secure: S5wgNSYY0Jthe6P0gp+gz8S1wgPdjIcbKxVyuNMLfqKPAfngcXT/I9wgeYmHYwN7
  bucket: layoric-deploy
  set_public: false
  folder: release
  artifact: release-deploy.zip